services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: cotali
      POSTGRES_PASSWORD: cotali
      POSTGRES_USER: cotali
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U cotali -d cotali']
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - '5432:5432'
    volumes:
      - cotali_postgres_data:/var/lib/postgresql/data

volumes:
  cotali_postgres_data:
