import {
  VoiceInterpretationSchema,
  VoiceQuoteEditInterpretationSchema,
} from '@cotali/contracts';
import { Value } from '@sinclair/typebox/value';
import { describe, expect, it } from 'vitest';
import './index';

describe('voice interpretation validation', () => {
  it('accepts the UUID and ISO dates generated by the interpreter', () => {
    const interpretation = {
      id: '73070f7c-a464-47d7-90bf-b06ac2ce7a1e',
      transcript: 'Trocar uma tomada por cem reais.',
      transcriptSegments: [],
      client: { name: null, phone: null },
      services: [
        {
          description: 'Trocar uma tomada',
          quantity: '1',
          unit: 'un',
          unitPriceInCents: 10_000,
        },
      ],
      materials: [],
      conditions: {
        paymentMethod: 'Pix',
        paymentPlanType: null,
        installmentCount: null,
        executionDeadline: null,
        validUntil: null,
        notes: null,
      },
      discountInCents: null,
      ambiguities: [],
      source: 'interpretation' as const,
      createdAt: '2026-09-03T23:00:00.000Z',
    };

    expect(Value.Check(VoiceInterpretationSchema, interpretation)).toBe(true);
  });

  it('accepts a client name edit command', () => {
    const interpretation = {
      id: '73070f7c-a464-47d7-90bf-b06ac2ce7a1e',
      transcript: 'Altere o nome do cliente para Roberto Pedro Pereira.',
      command: {
        ambiguities: [],
        changes: {
          clientName: 'Roberto Pedro Pereira',
          description: null,
          quantity: null,
          unit: null,
          unitPriceInCents: null,
        },
        index: null,
        intent: 'update_client' as const,
        section: 'client' as const,
      },
      source: 'command' as const,
      createdAt: '2026-09-03T23:00:00.000Z',
    };

    expect(
      Value.Check(VoiceQuoteEditInterpretationSchema, interpretation),
    ).toBe(true);
  });

  it('accepts a quantity expressed in hundredths in an edit command', () => {
    expect(
      Value.Check(VoiceQuoteEditInterpretationSchema, {
        id: '73070f7c-a464-47d7-90bf-b06ac2ce7a1e',
        transcript: 'Altere a quantidade para zero vírgula zero oito.',
        command: {
          ambiguities: [],
          changes: {
            clientName: null,
            description: null,
            quantity: '0.08',
            unit: null,
            unitPriceInCents: null,
          },
          index: 0,
          intent: 'update_line',
          section: 'materials',
        },
        source: 'command',
        createdAt: '2026-09-03T00:00:00.000Z',
      }),
    ).toBe(true);
  });
});
