import { VoiceInterpretationSchema } from '@cotali/contracts';
import { Value } from '@sinclair/typebox/value';
import { describe, expect, it } from 'vitest';
import './index';

describe('voice interpretation validation', () => {
  it('accepts the UUID and ISO dates generated by the interpreter', () => {
    const interpretation = {
      id: '73070f7c-a464-47d7-90bf-b06ac2ce7a1e',
      transcript: 'Trocar uma tomada por cem reais.',
      transcriptSegments: [],
      client: { name: null, phone: null },
      services: [
        {
          description: 'Trocar uma tomada',
          quantity: '1',
          unit: 'un',
          unitPriceInCents: 10_000,
        },
      ],
      materials: [],
      conditions: {
        paymentMethod: 'Pix',
        paymentPlanType: null,
        installmentCount: null,
        executionDeadline: null,
        validUntil: null,
        notes: null,
      },
      discountInCents: null,
      ambiguities: [],
      source: 'interpretation' as const,
      createdAt: '2026-09-03T23:00:00.000Z',
    };

    expect(Value.Check(VoiceInterpretationSchema, interpretation)).toBe(true);
  });
});
